#!/usr/bin/env python3
"""scripts/build_canonical_labels_md.py — generate the canonical-labels reference.

Reads config/taxonomy_v5.yaml (the single source of truth for the S4
taxonomy) and emits a human-readable markdown reference of ALL canonical
discipline + domain labels with their group and definition, plus the 4-way
depth ontology. Supports the P5 human-adjudication review pack and any
labeling work that must stay inside the canonical vocabulary.

Read-only. Writes governance/canonical_labels_reference.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

import yaml  # noqa: E402

_TAX = _ROOT / "config" / "taxonomy_v5.yaml"
_OUT = _ROOT / "governance" / "canonical_labels_reference.md"

_DEPTH = [
    ("universal", "Applies to ALL systems (physics, cooking, poetry)."),
    ("cross-domain", "Bridges 2+ DISTINCT disciplines via a SHARED mechanism."),
    ("domain", "Operates within ONE field / a cluster of adjacent fields."),
    ("specialized", "Narrow sub-technique within a sub-field or tool-specific skill."),
]


def _render_section(title: str, entries: list[dict], include_raw: bool) -> list[str]:
    """Render a group->(canonical: definition) section from taxonomy entries."""
    lines: list[str] = [f"## {title}", ""]
    by_group: dict[str, list[dict]] = {}
    for e in entries:
        by_group.setdefault(e.get("group", "Uncategorized"), []).append(e)
    for group in sorted(by_group):
        lines.append(f"### {group}")
        lines.append("")
        lines.append("| Canonical label | Definition |")
        lines.append("|---|---|")
        for e in sorted(by_group[group], key=lambda x: x["canonical"]):
            if e.get("canonical") == "emerging":
                continue  # rendered separately below
            lines.append(f"| `{e['canonical']}` | {e.get('definition', '')} |")
        lines.append("")
    return lines


def main() -> int:
    tax = yaml.safe_load(_TAX.read_text(encoding="utf-8")) or {}
    disciplines: list[dict] = tax.get("disciplines", [])
    domains: list[dict] = tax.get("domains", [])
    v = tax.get("version", "?")
    cv = tax.get("classification_version", "?")

    md: list[str] = [
        "# CANONICAL LABELS REFERENCE (S4 taxonomy)",
        "",
        f"Source of truth: `config/taxonomy_v5.yaml` ({v}, classification {cv}) — "
        "loaded via `pipeline/schemas.py::load_taxonomy()`. "
        "Generated by `scripts/build_canonical_labels_md.py`. "
        "DO NOT hand-edit this file; regenerate from the taxonomy.",
        "",
        "**Use for P5 human adjudication and all labeling: pick ONLY from these "
        "canonical labels.** `emerging` is the fail-closed catch-all (never a "
        "real assignment).",
        "",
        f"- **Disciplines:** "
        f"{len([d for d in disciplines if d.get('canonical') != 'emerging'])} "
        f"canonical (+ `emerging` catch-all)",
        f"- **Domains:** "
        f"{len([d for d in domains if d.get('canonical') != 'emerging'])} "
        f"canonical (+ `emerging` catch-all)",
        "- **Depth:** 4-way ontology "
        "(universal / cross-domain / domain / specialized)",
        "",
        "---",
        "",
    ]
    md += _render_section("DISCIPLINES (single-label — choose EXACTLY ONE)", disciplines, True)
    md += ["", "---", ""]
    md += _render_section("DOMAINS (multi-label — choose 1..3)", domains, False)
    md += [
        "",
        "---",
        "",
        "## DEPTH (choose EXACTLY ONE)",
        "",
        "| Depth | Meaning |",
        "|---|---|",
        *[f"| `{d}` | {desc} |" for d, desc in _DEPTH],
        "",
        "## Catch-all",
        "",
        "- `emerging` — fail-closed catch-all for disciplines/domains/depth that "
        "resolve to NO canonical label (unresolved or open-world). Never a "
        "deliberate assignment; a signal that the taxonomy needs a label or "
        "the FB needs review.",
        "",
        "## Aliasing notes",
        "",
        "- Each canonical entry carries a `raw` alias list (many surface forms "
        "map to one canonical) and an `exclude` list (near-neighbour labels to "
        "avoid). When adjudicating, match MEANING to the canonical definition, "
        "not to surface wording.",
        "- Domain groups (e.g. Visual Practice, Systems & Method) are for "
        "organization only — grouping is NOT a label axis.",
        "",
    ]
    _OUT.write_text("\n".join(md), encoding="utf-8")
    n_disc = sum(1 for d in disciplines if d.get("canonical") != "emerging")
    n_dom = sum(1 for d in domains if d.get("canonical") != "emerging")
    print(f"wrote {_OUT} | disciplines={n_disc} (+emerging) | domains={n_dom} (+emerging)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
