#!/usr/bin/env python3
"""judge_calibration.py — score the candidate cross-family judges against the blind human labels.

WHY (G3 / finding F-10). Six decision-list scripts judge objects that were generated by
`Qwen3-Coder` while judging with `Qwen3.8` — SAME family, so they agree on each other's mistakes and
every verdict is uninformative. A replacement verifier must come from a different family, but its
accuracy on THESE tasks is unmeasured. This script measures it, so the substitute is chosen by
evidence instead of intuition.

Method: run each candidate over the identical rows the human answered blind, then compare. The
human answered FIRST and saw no model output, so the comparison measures accuracy rather than
obedience (`governance/HUMAN_GATE_RUBRIC_20260917.md`).

Honesty rules enforced here:
  * a human verdict outside the allowed set is NORMALISED only for pure wording differences
    (case / whitespace / underscore / a clear synonym); a genuine third state such as `inbetween` is
    NEVER coerced into a binary answer — those rows are reported separately and excluded from the
    accuracy denominator, and the count is printed;
  * low-confidence rows are never dropped from the headline number (that would inflate the judge,
    the same selection trap that makes the 0.854 discipline figure unusable);
  * no model is called until the human column is complete.

Everything configurable lives in `config/eval_integrity.yaml::judge_calibration` (C12).

Usage:
  python3 scripts/judge_calibration.py --dry-run          # show prompts, call nothing
  python3 scripts/judge_calibration.py --limit 2          # smoke test
  python3 scripts/judge_calibration.py                    # full run
"""
from __future__ import annotations

import argparse
import collections
import csv
import json
import sys
import time
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SHEET = ROOT / "governance" / "JUDGE_CALIBRATION_SHEET_20260917.csv"
CFG = ROOT / "config" / "eval_integrity.yaml"
OUT_JSON = ROOT / "governance" / "judge_calibration_20260917.json"
OUT_MD = ROOT / "governance" / "judge_calibration_20260917.md"

REASONING_PREFIX = "Reasoning: low\n"
MAX_TOKENS = 512
UNDERSCORE = "_"

# Wording normalisation only. Deliberately explicit: an unseen value must fall through to
# "out of set" rather than being silently coerced (BUG-267 class).
SYNONYMS = {
    "differ": "different",
    "different": "different",
    "same": "same",
    "merge": "merge",
    "keep": "keep",
    "justified": "justified",
    "not justified": "not_justified",
    "not_justified": "not_justified",
    "unjustified": "not_justified",
    "tool instruction": "tool_instruction",
    "process template": "process_template",
    "process instance": "process_instance",
    "growth edge": "growth_edge",
    "noise drop": "noise_drop",
}
# A genuine third state a binary question cannot express. Reported, never coerced.
THIRD_STATE = {"inbetween", "in-between", "borderline", "partial", "mixed"}

OBJECT_FIELDS = ("object_1_name", "object_1_definition", "object_1_application",
                 "object_2_name", "object_2_definition", "object_2_application",
                 "object_3_name", "object_3_definition", "other_members_in_group",
                 "source_text_excerpt", "claimed_labels")


def load_cfg() -> dict[str, Any]:
    """Load the calibration config (candidates + decision thresholds)."""
    import yaml

    return (yaml.safe_load(CFG.read_text()) or {}).get("judge_calibration") or {}


def norm(value: str) -> str:
    """Lowercase, collapse separators, then apply the explicit synonym table."""
    text = " ".join(str(value or "").strip().lower().replace(UNDERSCORE, " ").split())
    return SYNONYMS.get(text, text.replace(" ", UNDERSCORE) if text in SYNONYMS.values() else text)


def allowed_set(row: dict[str, str]) -> list[str]:
    """Return the normalised allowed answers for a row, read from the sheet itself (C12)."""
    return [norm(a) for a in row["allowed_answer"].split("/") if a.strip()]


def human_label(row: dict[str, str]) -> tuple[str, str]:
    """Return (label, state) where state is decisive | third_state | out_of_set."""
    raw = " ".join(str(row.get("HUMAN_VERDICT") or "").strip().lower().split())
    if not raw:
        return "", "missing"
    if raw in THIRD_STATE:
        return raw, "third_state"
    label = norm(raw)
    if label in allowed_set(row):
        return label, "decisive"
    return raw, "out_of_set"


def render(row: dict[str, str]) -> str:
    """Render the object material a judge needs, in the same order the human saw it."""
    lines: list[str] = []
    for field in OBJECT_FIELDS:
        value = " ".join(str(row.get(field) or "").split())
        if not value:
            continue
        label = field.replace("_", " ")
        lines.append(label.upper() + ": " + value[:900])
    return "\n".join(lines)


def build_prompt(row: dict[str, str]) -> str:
    """Build the judge prompt for one row from the sheet's own question and answer set."""
    return (REASONING_PREFIX + row["QUESTION"].strip() + "\n\n"
            + render(row) + "\n\n"
            + "Answer with JSON only: {\"answer\": \"<one of: "
            + " | ".join(allowed_set(row)) + ">\"}")


def parse_answer(raw: str, allowed: list[str]) -> str:
    """Extract the model's answer and snap it to the allowed set; '' when nothing matches."""
    text = " ".join(str(raw or "").lower().replace('"', " ").replace(",", " ").split())
    for candidate in allowed:
        if candidate in text:
            return candidate
    for candidate in allowed:
        word = candidate.split(UNDERSCORE)[-1]
        if word and word in text:
            return candidate
    return ""


def run_judge(model: str, rows: list[dict[str, str]], limit: int, dry: bool) -> dict[str, str]:
    """Call one judge over every row and return {item_id: answer}. All calls for one model are
    grouped so the oMLX single-resident model swaps once (BUG-255: swapping wedges in-flight work)."""
    from pipeline.omlx_call import call_omlx_json

    out: dict[str, str] = {}
    subset = rows[:limit] if limit else rows
    for index, row in enumerate(subset, 1):
        prompt = build_prompt(row)
        if dry:
            print("\n" + "=" * 88 + "\n" + model + "  " + row["item_id"] + "\n" + "=" * 88)
            print(prompt[:1200])
            out[row["item_id"]] = ""
            continue
        started = time.time()
        answer = ""
        try:
            parsed = call_omlx_json(prompt, model=model, max_tokens=MAX_TOKENS)
            if isinstance(parsed, dict):
                answer = parse_answer(parsed.get("answer", ""), allowed_set(row))
            if not answer:
                answer = parse_answer(json.dumps(parsed), allowed_set(row))
        except Exception as exc:  # noqa: BLE001 — a judge failure must be visible, never silent (C16)
            print("    ERROR " + row["item_id"] + ": " + type(exc).__name__, flush=True)
        out[row["item_id"]] = answer
        print("  " + model[:22].ljust(22) + row["item_id"].ljust(9)
              + (answer or "UNPARSED").ljust(18)
              + "%.1fs" % (time.time() - started), flush=True)
    return out


def score(rows: list[dict[str, str]], answers: dict[str, dict[str, str]],
          models: list[str]) -> dict[str, Any]:
    """Accuracy per task per model, over decisive rows only, with coverage and gaps reported."""
    tasks = sorted({r["task"] for r in rows})
    report: dict[str, Any] = {"tasks": {}, "models": models, "coverage": {}, "third_state": [],
                              "out_of_set": []}
    for row in rows:
        label, state = human_label(row)
        if state == "third_state":
            report["third_state"].append({"task": row["task"], "item_id": row["item_id"],
                                          "human": label})
        elif state == "out_of_set":
            report["out_of_set"].append({"task": row["task"], "item_id": row["item_id"],
                                         "human": label})
    for task in tasks:
        subset = [(r, human_label(r)[0]) for r in rows
                  if r["task"] == task and human_label(r)[1] == "decisive"]
        counts = collections.Counter(label for _, label in subset)
        baseline = (counts.most_common(1)[0][1] / len(subset)) if subset else None
        entry: dict[str, Any] = {"n_decisive": len(subset), "per_model": {},
                                 "majority_class": counts.most_common(1)[0][0] if subset else None,
                                 "majority_baseline": round(baseline, 4) if baseline else None}
        for model in models:
            hits = sum(1 for row, label in subset if answers.get(model, {}).get(row["item_id"]) == label)
            unparsed = sum(1 for row, _ in subset if not answers.get(model, {}).get(row["item_id"]))
            entry["per_model"][model] = {
                "accuracy": round(hits / len(subset), 4) if subset else None,
                "hits": hits,
                "unparsed": unparsed,
            }
        report["tasks"][task] = entry
    report["coverage"] = {
        "rows_total": len(rows),
        "decisive": sum(1 for r in rows if human_label(r)[1] == "decisive"),
        "third_state": len(report["third_state"]),
        "out_of_set": len(report["out_of_set"]),
    }
    return report


def decide(report: dict[str, Any], cfg: dict[str, Any]) -> dict[str, str]:
    """Apply the config decision rule per task and return {task: verdict}."""
    adopt = float(cfg.get("min_accuracy_adopt", 0.85))
    cond = float(cfg.get("min_accuracy_conditional", 0.70))
    verdicts: dict[str, str] = {}
    for task, entry in report["tasks"].items():
        scored = {m: v for m, v in entry["per_model"].items() if v["accuracy"] is not None}
        if not scored:
            verdicts[task] = "NO_DECISIVE_ROWS — regenerate the sheet for this task"
            continue
        best = max(scored.items(), key=lambda kv: (kv[1]["accuracy"], -kv[1]["unparsed"]))
        accuracy = float(best[1]["accuracy"])
        baseline = float(entry.get("majority_baseline") or 0.0)
        margin = float(cfg.get("min_margin_over_baseline", 0.15))
        lift = accuracy - baseline
        tag = ("%" + "s acc=%.3f vs baseline %.3f (lift %+.3f)") % (best[0], accuracy, baseline, lift)
        if lift < margin:
            verdicts[task] = ("DEGENERATE — " + tag + " — the judge adds no information over the "
                              "constant answer '" + str(entry.get("majority_class"))
                              + "'; make this task deterministic or human-owned")
        elif accuracy >= adopt:
            verdicts[task] = "ADOPT " + tag + " as the verifier"
        elif accuracy >= cond:
            verdicts[task] = "CONDITIONAL " + tag + " — record the error bar, escalate disagreements"
        else:
            verdicts[task] = "NO JUDGE — " + tag + " — make this task deterministic or human-owned"
    return verdicts


def _rescore(cfg: dict[str, Any], models: list[str], sheet: Path) -> None:
    """Re-score the stored raw answers against the sheet, applying the current rule (no calls)."""
    prior = json.loads(OUT_JSON.read_text())
    with sheet.open(newline="") as fh:
        rows = [r for r in csv.DictReader(fh)]
    report = score(rows, prior["raw_answers"], models)
    report["verdicts"] = decide(report, cfg)
    report["measured_at"] = prior.get("measured_at", "")
    report["sheet"] = prior.get("sheet", "")
    report["raw_answers"] = prior["raw_answers"]
    OUT_JSON.write_text(json.dumps(report, indent=2))
    _write_md(report, models)
    print("re-scored from stored answers (no model calls)\n" + "=" * 88)
    for task, entry in sorted(report["tasks"].items()):
        print("  " + task.ljust(20) + "baseline=" + str(entry["majority_baseline"])
              + " (" + str(entry["majority_class"]) + ")")
    for task, verdict in sorted(report["verdicts"].items()):
        print("  " + task.ljust(20) + verdict)


def _write_md(report: dict[str, Any], models: list[str]) -> None:
    """Write the human-readable verdict, always showing the majority-class baseline.

    The baseline column is the point of the table: a judge at 0.778 on a task whose constant answer
    already scores 0.778 carries no information, and a bare accuracy column hides that.
    """
    lines = ["# Judge calibration — measured verdict (G3)", "",
             "Sheet: `" + report.get("sheet", "") + "` | measured " + report.get("measured_at", ""), "",
             "Human answered **first and blind**. Wording differences were normalised; a genuine "
             "third state was **not** coerced. `lift` = accuracy − the constant-answer baseline: a "
             "judge must beat it by the configured margin or it is **degenerate** "
             "(`config/eval_integrity.yaml::judge_calibration`).", "",
             "## Decision", "", "| task | verdict |", "|---|---|"]
    lines += ["| `" + t + "` | " + v + " |" for t, v in sorted(report["verdicts"].items())]
    lines += ["", "## Accuracy vs the constant-answer baseline", "",
              "| task | n | baseline | baseline label | " + " | ".join("`" + m + "`" for m in models) + " |",
              "|---|---|---|---|" + "---|" * len(models)]
    for task, entry in sorted(report["tasks"].items()):
        cells = []
        for model in models:
            stat = entry["per_model"][model]
            acc = "n/a" if stat["accuracy"] is None else ("%.3f" % stat["accuracy"])
            lift = ("" if stat["accuracy"] is None else " (lift %+.2f)" % (stat["accuracy"] - float(entry["majority_baseline"] or 0)))
            cells.append(acc + lift + ("" if not stat["unparsed"] else " [" + str(stat["unparsed"]) + " unparsed]"))
        lines.append("| `" + task + "` | " + str(entry["n_decisive"]) + " | "
                     + ("%.3f" % float(entry["majority_baseline"] or 0)) + " | `"
                     + str(entry["majority_class"]) + "` | " + " | ".join(cells) + " |")
    cov = report["coverage"]
    lines += ["", "## Coverage (reported, never silently dropped)", "",
              "- rows total: **" + str(cov["rows_total"]) + "**",
              "- decisive (scored): **" + str(cov["decisive"]) + "**",
              "- third state (`inbetween` etc., excluded from the denominator): **"
              + str(cov["third_state"]) + "**",
              "- out of set: **" + str(cov["out_of_set"]) + "**"]
    if report["third_state"]:
        lines += ["", "### Rows with no binary answer", ""]
        lines += ["- `" + x["task"] + "` / `" + x["item_id"] + "` — human said `" + x["human"] + "`"
                  for x in report["third_state"]]
        lines += ["", "A forced binary under-describes these rows (the same signal as G2's "
                      "`quarantine`). Report it; do not coerce it."]
    if report["out_of_set"]:
        lines += ["", "### Out-of-set verdicts (not normalisable)", ""]
        lines += ["- `" + x["task"] + "` / `" + x["item_id"] + "` — human said `" + x["human"] + "`"
                  for x in report["out_of_set"]]
    lines += ["", "## Caveat", "",
              "n is small per task (7-9 decisive rows). Treat these as **indicative**: they are "
              "enough to reject a judge that does not beat the constant answer, not enough to "
              "certify one. The proper instrument (Krippendorff alpha + a per-task n_min) is still "
              "unbuilt — market research A1/A2."]
    OUT_MD.write_text("\n".join(lines) + "\n")


def main() -> int:
    """Run the calibration for every configured candidate and write the verdict artifact."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=0, help="only the first N rows (smoke test)")
    ap.add_argument("--dry-run", action="store_true", help="print prompts, call no model")
    ap.add_argument("--models", default="", help="comma-separated override of the candidates")
    ap.add_argument("--rescore", action="store_true",
                    help="re-score the stored raw answers (no model calls) after a rule change")
    args = ap.parse_args()

    cfg = load_cfg()
    models = [m.strip() for m in args.models.split(",") if m.strip()] or list(cfg.get("candidates") or [])
    if args.rescore:
        prior = json.loads(OUT_JSON.read_text())
        rows_stored = [{"task": a["task"], "item_id": a["item_id"]} for a in prior["raw_answers"][models[0]].values()] if False else None
        _rescore(cfg, models, SHEET)
        return 0
    if not models:
        raise SystemExit("no candidate models in config/eval_integrity.yaml::judge_calibration")

    with SHEET.open(newline="") as fh:
        rows = [r for r in csv.DictReader(fh)]
    pending = [r for r in rows if not (r.get("HUMAN_VERDICT") or "").strip()]
    if pending:
        raise SystemExit(str(len(pending)) + " row(s) still unanswered — calibrating against an "
                         "incomplete human column would measure nothing")
    print("rows " + str(len(rows)) + " | candidates " + ", ".join(models)
          + " | limit " + (str(args.limit) if args.limit else "all"))

    answers = {model: run_judge(model, rows, args.limit, args.dry_run) for model in models}
    if args.dry_run:
        return 0

    report = score(rows, answers, models)
    verdicts = decide(report, cfg)
    report["verdicts"] = verdicts
    report["measured_at"] = time.strftime("%Y-%m-%dT%H:%M:%S")
    report["sheet"] = str(SHEET.relative_to(ROOT))
    report["raw_answers"] = answers

    OUT_JSON.write_text(json.dumps(report, indent=2))
    _write_md(report, models)


    print("\n" + "=" * 88)
    for task, verdict in sorted(verdicts.items()):
        print("  " + task.ljust(20) + verdict)
    print("\ncoverage: " + json.dumps(cov))
    print("artifacts: " + str(OUT_JSON.name) + " + " + str(OUT_MD.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
