NEW_EXAMPLES = [
    {
        "id": "DES-001",
        "domain": "design",
        "content_type": "principle",
        "source_text": "The process of composition is the most crucial step in visual problem solving. The results of the compositional decisions set the purpose and meaning of the visual statement and carry strong implications for what the viewer receives. It is at this vital stage in the creative process that the visual communicator has the strongest control of the work and the greatest opportunity to express the total mood the work is intended to convey. But the visual mode offers no proscribed structural systems that are absolute. How can we gain control of our complex visual means with some certainty of shared meaning? There are no absolute rules, but there is a great deal of understanding of what will occur in terms of meaning if we make certain arrangements of the parts toward organizing and orchestrating the visual means.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "Composition is the highest-leverage stage in visual communication \u2014 it is where the communicator has maximum control over meaning and mood, yet visual language lacks absolute rules, requiring designers to develop a deep understanding of how compositional arrangements predictably shape viewer interpretation.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Core design principle from a foundational visual literacy textbook. Identifies the causal relationship: compositional decisions \u2192 viewer interpretation. Acknowledges the tension between control and the absence of absolute rules \u2014 a defining characteristic of design as a discipline.",
    },
    {
        "id": "DES-002",
        "domain": "design",
        "content_type": "principle",
        "source_text": "The more abstract the symbol, the more penetration of the public mind is necessary for the education to its meaning. A dove carrying an olive branch became the easily recognized symbol of peace only after widespread cultural education. In this case, some education of the public may be necessary for the message to be clear. But the more abstract the symbol, the more prior knowledge the viewer must bring to decode it.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "Symbol abstraction and audience education are inversely proportional: the more abstract a visual symbol, the more cultural penetration and public education is required before it can reliably communicate its intended meaning. Concrete symbols require less decoding effort than abstract ones.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Establishes a gradient from concrete to abstract symbol systems and the educational burden each places on the viewer. A fundamental semiotic principle with direct application to logo design, iconography, and visual communication.",
    },
    {
        "id": "DES-003",
        "domain": "design",
        "content_type": "principle",
        "source_text": "For the initial stage, a designer must not fear making mistakes. Now is not the time to worry about the clarity, spacing, form, or silhouette. Instead sketching should be performed as a fever-like activity, pouring ideas on the paper. The more unrestrained, spontaneous, unconscious, and uninhibited, the better. This should be viewed as an exploratory stage where anything is allowed. A designer must generate volume before editing \u2014 quantity precedes quality in the ideation phase.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "In the ideation phase of design, quantity precedes quality: unrestrained, spontaneous sketching without concern for clarity or correctness produces the raw volume from which strong concepts can later be selected and refined. Premature self-editing kills exploration.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Actionable design process principle. Establishes a two-phase model (divergent exploration \u2192 convergent editing) that applies across all design disciplines.",
    },
    {
        "id": "DES-004",
        "domain": "design",
        "content_type": "principle",
        "source_text": "The body of work created by modernists laid a solid foundation for modern logo designs. A certain language of form was invented, and there are certain elements that represent a fabric of modernist aesthetic. These include waves, stripes, stars, arrows, cubes, overlapping primitive shapes with exclusion, inclusion, and intersection. Geometric precision was favored over the expressive, and universal appeal was valued over a culture-bound aesthetic.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "Modernist design established a universal visual language built on geometric primitives (waves, stripes, stars, arrows, cubes) and boolean operations (exclusion, inclusion, intersection). It prioritized geometric precision and universal appeal over cultural specificity and personal expression.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Defines the modernist design language that underpins contemporary logo design. Establishes vocabulary (geometric primitives + boolean operations) and value system (universal over culture-specific).",
    },
    {
        "id": "DES-005",
        "domain": "design",
        "content_type": "principle",
        "source_text": "Corporate type must be simple and readable; it must also use a neutral sans serif type for main text. Most of the time I advise clients to use a simple sans serif because it's neutral, simple to use, and most devices have it as a default font, meaning it will not be an additional cost. Corporate typography is often a different entity from the logo type \u2014 though not always.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "Corporate typography should prioritize neutrality and ubiquity over distinction: simple sans-serif fonts ensure readability, cross-platform consistency, and zero licensing cost \u2014 separating the functional role of corporate type from the expressive role of logo marks.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Practical decision heuristic for typography selection in identity systems. Separates corporate type concerns from logo type concerns.",
    },
    {
        "id": "DES-006",
        "domain": "design",
        "content_type": "principle",
        "source_text": "A dot alone in a field relates to the whole, but it stands alone, and the relationship is a mild state of intermodification between it and the square. But when two dots are placed in the same field, they fight for attention in their interaction, creating comparatively individual statements because of their distance from each other and their relationship to the frame. The introduction of a second element transforms a static field into a dynamic composition.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "A single element in a visual field creates a static relationship with the frame, but adding a second element transforms the composition into a dynamic system of competing attention \u2014 each element now interacts with the other and the frame, making spatial relationships the primary carriers of meaning.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Fundamental compositional principle identifying the threshold between static and dynamic composition (one element \u2192 two elements). Generalizes beyond dots to any design elements.",
    },
    {
        "id": "ART-001",
        "domain": "art",
        "content_type": "principle",
        "source_text": "A 'North Star' for instrument design is to create something 'instantly knowable, yet infinitely masterable.' Consider the pencil, or the piano: its basic principles of operation are simple enough for a child to deduce, yet one can spend a lifetime using it and still find more to say; sophisticated expressions are possible, and mastery is elusive. From the standpoint of systems design, our challenge is to create tools that have this same property: a low floor, a high ceiling, and wide walls.",
        "source_book": "Code as Creative Medium \u2014 Golan Levin & Tega Brain",
        "expected_principles": [
            "The ideal creative instrument has three properties: a low floor (simple enough for a novice to start immediately), a high ceiling (capable of sophisticated expression by experts), and wide walls (supporting diverse approaches and styles). This 'instantly knowable, yet infinitely masterable' quality is the North Star for tool, language, and interface design.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Widely-cited design framework for creative tools (low floor, high ceiling, wide walls). Originated in computational art education but generalizes to any creative instrument. High-reuse principle.",
    },
    {
        "id": "ART-002",
        "domain": "art",
        "content_type": "principle",
        "source_text": "In computational art and design, many responses to the questions of what and why continue historic lines of creative inquiry centered on procedure, connection, abstraction, authorship, the nature of time, and the role of chance. The pursuit of these formal and conceptual concerns in the medium of computation has created new practices and aesthetics, and has also heightened a sensibility to the formal properties of code itself \u2014 that code is not merely a tool but a material with its own affordances and constraints.",
        "source_book": "Code as Creative Medium \u2014 Golan Levin & Tega Brain",
        "expected_principles": [
            "Computational art extends historic creative concerns (procedure, abstraction, authorship, time, chance) into a new medium, but with a critical distinction: code is not merely a neutral tool but a material with its own affordances and constraints that shape the resulting work. The medium is part of the message.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Establishes the philosophical foundation of computational art: it engages with the material properties of code as medium, not just uses code as a tool. Connects to broader media theory.",
    },
    {
        "id": "ART-003",
        "domain": "art",
        "content_type": "principle",
        "source_text": "Computers and computing were not the same thing. What hadn't been made apparent to me during my university days was that computation is an abstract idea, not a physical machine. It's the manipulation of ideas according to formal rules. A computer is just one possible embodiment of this idea. Once I understood that computing wasn't about machines but about process and logic, a whole new world of creative possibility opened up.",
        "source_book": "Generative Art: A Practical Guide \u2014 Matt Pearson",
        "expected_principles": [
            "Computation is an abstract idea \u2014 the manipulation of concepts according to formal rules \u2014 not a physical machine. A computer is merely one embodiment of computation. Recognizing this distinction unlocks creative approaches: computation can be expressed in any medium, not just electronics.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Fundamental reframing that separates the concept of computation from its physical implementation. The intellectual move that makes generative art possible.",
    },
    {
        "id": "ART-004",
        "domain": "art",
        "content_type": "principle",
        "source_text": "Some parts bubble and then fade out; others achieve a looping stability. There has been much study of this game, identifying the mathematical 'life' that forms: gliders, toads, boats, blinkers, blocks. What makes Conway's Game of Life so compelling for generative artists is that complex, seemingly organic behavior emerges from a tiny set of deterministic rules applied locally to each cell. You don't design the pattern \u2014 you design the rules, and the pattern designs itself.",
        "source_book": "Generative Art: A Practical Guide \u2014 Matt Pearson",
        "expected_principles": [
            "Generative art operates on emergence: complex, organic-seeming behavior arises from simple, local, deterministic rules applied iteratively. The artist's role shifts from designing the output to designing the rule system \u2014 you don't design the pattern, you design the rules, and the pattern designs itself.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Defines the core mechanism of generative art: emergence from rule systems. The distinction between designing outputs vs. designing rules is the defining characteristic of the field.",
    },
    {
        "id": "ART-005",
        "domain": "art",
        "content_type": "principle",
        "source_text": "Humans are equipped with an exquisite sensitivity to faces. From infancy, we easily recognize faces and can detect very subtle shifts in expressions, often being able to discern the slightest change in mood and sincerity in ways that remain impossible for computers. Faces also allow us to readily identify family resemblances or recognize friends in crowds. Faces are so central to visual perception that the impairment of our face-processing ability is seen as a disorder, called prosopagnosia, while unconsciously seeing faces where there are none is an almost universal kind of pareidolia.",
        "source_book": "Code as Creative Medium \u2014 Golan Levin & Tega Brain",
        "expected_principles": [
            "Human face perception occupies a privileged channel in visual cognition: we detect faces instantly, read micro-expressions beyond computer capability, and hallucinate faces in random patterns (pareidolia). This makes face-like forms a uniquely powerful design material that commands attention regardless of context.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Establishes face perception as a design primitive with unique properties. The pareidolia/prosopagnosia contrast demonstrates the depth of this neural mechanism. Actionable for character, icon, and visualization design.",
    },
    {
        "id": "ART-006",
        "domain": "art",
        "content_type": "principle",
        "source_text": "This assignment draws inspiration from the 'Chernoff face' data visualization technique, which leverages this sensitivity by using facial features to represent multivariate data. In Chernoff faces, features such as the eyes, ears, mouth, and nose represent data according to their shape, size, placement, and orientation. Whereas Herman Chernoff used 18 variables to synthesize a face, Paul Ekman and Wallace Friesen's Facial Action Coding System analyzes faces with 46, each variable corresponding to the action of a different facial muscle.",
        "source_book": "Code as Creative Medium \u2014 Golan Levin & Tega Brain",
        "expected_principles": [
            "Chernoff faces exploit the human brain's specialized face-processing circuitry for data visualization: facial features (eyes, ears, mouth, nose) encode multivariate data through shape, size, placement, and orientation. This technique maps up to 18 data dimensions onto a single glyph by piggybacking on evolutionarily-ancient perception hardware.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Concrete data visualization technique that bridges cognitive science (face perception) and design practice. The connection to Ekman's FACS system enriches the principle with scientific grounding.",
    },
    {
        "id": "PER-001",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Outcomes are about what you get. Processes are about what you do. Identity is about what you believe. When it comes to building habits that last \u2014 when it comes to building a system of 1 percent improvements \u2014 the problem is not that one level is 'better' or 'worse' than another. All levels of change are useful in their own way. The problem is the direction of change.",
        "source_book": "Atomic Habits \u2014 James Clear",
        "expected_principles": [
            "Behavior change operates on three levels: outcome (what you get), process (what you do), and identity (what you believe). The most durable change starts from identity outward \u2014 deciding who you want to become, then letting processes and outcomes follow \u2014 rather than starting with outcomes and hoping identity catches up.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Core framework from one of the most influential habit-formation books. The three-level model (outcome \u2192 process \u2192 identity) is a reusable mental model applicable beyond personal habits to organizational change, education, and coaching.",
    },
    {
        "id": "PER-002",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Imagine two people resisting a cigarette. When offered a smoke, the first person says, 'No thanks. I'm trying to quit.' It sounds like a reasonable response, but this person still believes they are a smoker who is trying to be something else. They are hoping their behavior will change while carrying around the same beliefs. The second person says, 'No thanks. I'm not a smoker.'",
        "source_book": "Atomic Habits \u2014 James Clear",
        "expected_principles": [
            "Identity-based resistance is more effective than willpower-based resistance: saying 'I'm not a smoker' (identity statement) outperforms 'I'm trying to quit' (effort statement) because the former aligns the behavior with a self-concept that makes the undesired action inconsistent with who the person believes themselves to be.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Demonstrates the identity-based change model with a concrete, testable example. The linguistic contrast ('I'm trying' vs. 'I'm not') makes the abstract principle tangible and memorable.",
    },
    {
        "id": "PER-003",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "The first three laws of behavior change \u2014 make it obvious, make it attractive, and make it easy \u2014 increase the odds that a behavior will be performed this time. The fourth law of behavior change \u2014 make it satisfying \u2014 increases the odds that a behavior will be repeated next time. It completes the habit loop.",
        "source_book": "Atomic Habits \u2014 James Clear",
        "expected_principles": [
            "The Four Laws of Behavior Change form a complete loop: make it obvious (cue), make it attractive (craving), make it easy (response), and make it satisfying (reward). The first three drive initiation; the fourth drives repetition. Without satisfaction, behaviors extinguish regardless of how easy or obvious they are.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Summarizes the book's central framework. Each law maps to a phase in the habit loop (cue/craving/response/reward), connecting practical advice to behavioral psychology. High reuse potential.",
    },
    {
        "id": "PER-004",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "The more automatic a behavior becomes, the less likely we are to consciously think about it. And when we've done something a thousand times before, we begin to overlook things. We assume that the next time will be just like the last. We're so used to doing what we've always done that we don't stop to question whether it's the right thing to do at all. Many of our failures in performance are largely attributable to a lack of self-awareness.",
        "source_book": "Atomic Habits \u2014 James Clear",
        "expected_principles": [
            "Automaticity creates a blindness trap: the more practiced a behavior becomes, the less conscious attention we pay to it, causing us to overlook errors, assume stability, and fail to question whether the behavior is still appropriate. Mastery requires deliberate disruption of automaticity \u2014 periodic re-examination of what has become invisible through repetition.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Identifies a paradox of expertise: the very automaticity that enables high performance also creates vulnerability to stale thinking. Applies broadly beyond habits to professional practice, organizational routines, and skill development.",
    },
    {
        "id": "PER-005",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Resistance seems to come from outside ourselves. We locate it in spouses, jobs, bosses, kids. 'Peripheral opponents,' as Pat Riley used to say when he coached the Los Angeles Lakers. Resistance is not a peripheral opponent. Resistance arises from within. It is self-generated and self-perpetuated. Resistance is the enemy within.",
        "source_book": "The War of Art \u2014 Steven Pressfield",
        "expected_principles": [
            "Resistance \u2014 the force that prevents creative work \u2014 feels external but is internally generated. We project it onto spouses, bosses, and circumstances, but it originates within. Recognizing Resistance as self-generated rather than externally imposed is the first step to overcoming it, because external enemies can be avoided; internal ones must be confronted.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Core concept from a seminal book on creative practice. The internal vs. external attribution distinction is a psychological insight with practical consequences: if Resistance is internal, avoidance doesn't work \u2014 confrontation does.",
    },
    {
        "id": "PER-006",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Resistance will tell you anything to keep you from doing your work. It will perjure, fabricate, falsify; seduce, bully, cajole. Resistance is protean. It will assume any form, if that's what it takes to deceive you. It will reason with you like a lawyer or jam a nine-millimeter in your face like a stickup man. Resistance has no conscience. It will pledge anything to get a deal, then double-cross you as soon as your back is turned. If you take Resistance at its word, you deserve everything you get. Resistance is always lying and always full of shit.",
        "source_book": "The War of Art \u2014 Steven Pressfield",
        "expected_principles": [
            "Resistance is protean \u2014 it adapts its tactics to whatever will most effectively prevent the creative from doing the work, shifting between seduction, intimidation, rational argument, and outright deception. Because Resistance has no fixed form, the only reliable countermeasure is to recognize that it is always lying, regardless of how reasonable it sounds.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Describes the adaptive, shape-shifting nature of creative Resistance. The 'protean' quality means you cannot develop a single counter-strategy \u2014 you must recognize the pattern across its many forms. Expands Pressfield's framework beyond the initial definition.",
    },
    {
        "id": "PER-007",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "The paradox seems to be, as Socrates demonstrated long ago, that the truly free individual is free only to the extent of his own self-mastery. While those who will not govern themselves are condemned to find masters to govern over them.",
        "source_book": "The War of Art \u2014 Steven Pressfield",
        "expected_principles": [
            "Freedom and self-mastery are directly proportional, not opposed: the individual who cannot discipline themselves must submit to external discipline. Creative freedom requires the internal structure of a professional \u2014 showing up regardless of inspiration \u2014 because absence of internal governance invites external control.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Philosophical principle tracing back to Socratic thought, applied to creative practice. Inverts the common assumption that freedom means absence of discipline. High reuse across personal practice, leadership, and organizational design.",
    },
    {
        "id": "PER-008",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Once you see a pattern, you can't un-see it. Trust me, I've tried. But when the same truth keeps repeating itself, it's hard to pretend that it's just a coincidence. For example, no matter how hard I try to convince myself that I can function on six hours of sleep, anything less than eight hours leaves me impatient, anxious, and foraging for carbohydrates. It's a pattern.",
        "source_book": "The Gifts of Imperfection \u2014 Bren\u00e9 Brown",
        "expected_principles": [
            "Pattern recognition creates an irreversible awareness: once you've identified a recurring truth about yourself, you cannot return to the state of not-knowing. The data (e.g., 'I am irritable on less than eight hours of sleep') accumulates until denial becomes more costly than acceptance. Self-awareness is a one-way door.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Describes the psychological mechanism of self-awareness as irreversible pattern recognition. The 'one-way door' property means self-knowledge compounds \u2014 each pattern you see makes the next one easier to spot.",
    },
    {
        "id": "PER-009",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "Joy is as thorny and sharp as any of the dark emotions. To love someone fiercely, to believe in something with your whole heart, to celebrate a fleeting moment in time, to fully engage in a life that doesn't come with guarantees \u2014 these are risks that involve vulnerability and often pain. When we lose our tolerance for discomfort, we lose joy. In fact, addiction research shows us that an intensely positive experience can be as difficult to process as a traumatic one.",
        "source_book": "The Gifts of Imperfection \u2014 Bren\u00e9 Brown",
        "expected_principles": [
            "Joy and vulnerability are inseparable: the capacity to experience joy requires the capacity to tolerate the vulnerability that accompanies it \u2014 the risk of loss, the absence of guarantees. Numbing vulnerability doesn't selectively numb pain; it also numbs joy. This is why addiction research finds that intensely positive experiences can be as destabilizing as traumatic ones.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Inverts the common assumption that joy is 'light' and pain is 'heavy.' Establishes that vulnerability tolerance is the single mechanism underlying both \u2014 you cannot selectively suppress one without suppressing the other. Supported by addiction research.",
    },
    {
        "id": "DES-007",
        "domain": "design",
        "content_type": "principle",
        "source_text": "Syntax in the context of visual literacy can only mean the orderly arrangement of parts, leaving us with the problem of how we can approach the process of composition with intelligence and knowledge of how compositional decisions will affect the final result. There are no absolute rules, but there is a great deal of understanding of what will occur in terms of meaning if we make certain arrangements of the parts toward organizing and orchestrating the visual means. Many of the guidelines for understanding the meaning in visual form, the syntactic rules, are based on what we know about human perception.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "Visual syntax operates not as absolute rules but as predictive guidelines grounded in human perception: certain arrangements reliably produce certain interpretations because of how the human visual system processes information. Effective composition requires understanding these perceptual principles and applying them intelligently to the specific communicative goal, not following a fixed recipe.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Defines visual syntax as a perceptual science rather than an aesthetic rulebook. The distinction between 'absolute rules' and 'predictive guidelines grounded in perception' is fundamental to understanding design as a discipline.",
    },
    {
        "id": "DES-008",
        "domain": "design",
        "content_type": "principle",
        "source_text": "Transparency and opacity define each other physically: the former means visual detail that can be seen through so that what is behind it is revealed to the eye; the latter is just the opposite, blocking out, concealing what it visually supersedes. These two poles represent one of the fundamental technique polarities available to the visual communicator.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "Transparency and opacity form a fundamental visual polarity: transparency reveals layers and creates depth through visible relationships between foreground and background, while opacity conceals and creates hierarchy through visual dominance. Understanding this polarity gives the designer control over what the viewer sees first, second, and what remains hidden.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Defines a fundamental visual design polarity. The technique is simple but the implications for information hierarchy and visual storytelling are profound. A building-block principle for design education.",
    },
    {
        "id": "DES-009",
        "domain": "design",
        "content_type": "principle",
        "source_text": "Visual communication, like language, employs a set of symbols with agreed-upon meanings. Unlike language, however, visual communication has no fixed syntax \u2014 no equivalent of grammar that dictates how symbols must be combined. This absence of fixed rules is both a liberation and a burden: the designer has greater freedom but less certainty that the audience will interpret the work as intended.",
        "source_book": "A Primer of Visual Literacy \u2014 Donis A. Dondis",
        "expected_principles": [
            "Visual communication differs fundamentally from verbal language in one critical respect: it lacks a fixed grammar. This absence is a double-edged sword \u2014 it gives designers creative freedom unconstrained by syntactic rules, but it also removes the certainty of shared interpretation that grammar provides in verbal communication. Every visual message is therefore an act of faith in the audience's perceptual capabilities.",
        ],
        "should_extract": True,
        "principle_type": "comparative",
        "rationale": "Defines the fundamental difference between visual and verbal communication. The comparative structure (visual vs. language) makes this a rare comparative principle type \u2014 exactly what the golden set needs. The 'liberation and burden' framing captures the essential tension of design.",
    },
    {
        "id": "DES-010",
        "domain": "design",
        "content_type": "principle",
        "source_text": "The circle applied as a graphic device works well with a triangular mark since the negative space in relationship to circle and triangle appears balanced. If it was a square, the approach and result would differ. The interaction between the containing shape and the contained mark creates either harmony or tension, and the choice between them is never neutral \u2014 it communicates something about the brand.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "The relationship between a logo mark and its containing shape is never neutral: a circle creates balanced negative space with angular marks, while a square creates different tension dynamics. The choice of container shape is a communicative decision, not merely a compositional one \u2014 it shapes how the brand is perceived before the viewer even processes the mark itself.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Demonstrates a specific design principle (container-shape interaction) with concrete examples. The higher-order principle \u2014 that every formal choice is also a communicative choice \u2014 generalizes beyond logo design.",
    },
    {
        "id": "DES-011",
        "domain": "design",
        "content_type": "principle",
        "source_text": "Creating an effective combination of pattern and color can be difficult. Seeing how the pattern will re-create and repeat at different scales is a quick way to determine the overall effect. It can be helpful to both the designer and client to create mock-ups of the pattern in use in practical situations. Be sure to use a variety of sizes, such as on a letterhead or on a wall in an office.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "Pattern evaluation requires multi-scale testing: a pattern that works at business-card scale may fail as environmental graphics, and vice versa. The designer must test at every scale the pattern will inhabit \u2014 letterhead, signage, digital screen, textile \u2014 because scale changes the perceptual relationship between pattern elements and fundamentally alters the visual effect.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Practical design process principle. The multi-scale testing requirement applies to any repetitive visual system \u2014 patterns, grids, logos, typography. The insight that scale changes perceptual relationships is a fundamental design truth.",
    },
    {
        "id": "PER-010",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "The word compassion is derived from the Latin words pati and cum, meaning 'to suffer with.' I don't believe that compassion is our default response to suffering. I think our first response is usually self-protection. We armor ourselves against pain, or we try to fix it, or we resort to blame. Compassion is a practice \u2014 not a personality trait \u2014 that requires us to stay present with suffering without trying to solve it.",
        "source_book": "The Gifts of Imperfection \u2014 Bren\u00e9 Brown",
        "expected_principles": [
            "Compassion is a practice, not a personality trait. The etymology ('to suffer with') reveals that compassion requires the capacity to stay present with suffering \u2014 our own or others' \u2014 without armoring, fixing, or blaming. Because self-protection is the default response, compassion requires deliberate cultivation, not passive possession.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Redefines compassion from trait to practice, using etymology as evidence. The 'practice not trait' reframing has broad application: courage, vulnerability, and creativity can all be understood similarly. High reuse potential across personal practice and leadership.",
    },
    {
        "id": "PER-011",
        "domain": "personal_practice",
        "content_type": "principle",
        "source_text": "When we lose our tolerance for discomfort, we lose joy. In fact, addiction research shows us that an intensely positive experience can be as difficult to process as a traumatic one. We cannot selectively numb emotions. When we numb the dark, we also numb the light.",
        "source_book": "The Gifts of Imperfection \u2014 Bren\u00e9 Brown",
        "expected_principles": [
            "Emotional numbing is non-selective: you cannot suppress pain without also suppressing joy, vulnerability without also suppressing love, fear without also suppressing courage. The mechanism is binary \u2014 emotions share neural circuitry, so any dampening affects the entire spectrum. This explains why people who 'play it safe' emotionally often report feeling flat or numb rather than protected.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "A neuroscientifically-grounded principle about emotional processing. The 'non-selective numbing' insight has profound implications for mental health, creativity, leadership, and relationships. Supported by addiction research cited in the text.",
    },
    {
        "id": "ART-007",
        "domain": "art",
        "content_type": "principle",
        "source_text": "Generative design has long ceased to be a trade secret among design students; in some universities, it is now firmly integrated into the curriculum. From infographics to the visualization of sound, from the fine arts to architecture, and especially in the realm of communication design and media installations, generative design allows for dynamic, stunning, and fascinating applications.",
        "source_book": "Generative Design \u2014 Bohnacker, Gro\u00df, Laub, Lazzeroni",
        "expected_principles": [
            "Generative design has moved from experimental practice to mainstream curriculum across disciplines: infographics, sound visualization, fine arts, architecture, and communication design. Its defining value is dynamism \u2014 the ability to create systems that produce varied, responsive outputs rather than fixed artifacts \u2014 making it particularly suited to media installations and interactive contexts.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Marks the institutional adoption of generative design as a discipline. Defines the value proposition (dynamism over fixity) and maps the application landscape. Useful as a reference principle for understanding the field's scope.",
    },
    {
        "id": "ART-008",
        "domain": "art",
        "content_type": "principle",
        "source_text": "Processing and vvvv have for many years been the programming environments of choice for artists and designers. However, more recently there has been a shift toward more web-centric applications, giving rise to new coding environments such as p5.js, a JavaScript library that is especially programmed for and by artists, designers, and other web users. This shift reflects a broader movement: creative coding is moving from the desktop to the browser, from standalone applications to networked experiences.",
        "source_book": "Generative Design \u2014 Bohnacker, Gro\u00df, Laub, Lazzeroni",
        "expected_principles": [
            "Creative coding tools are migrating from desktop (Processing, vvvv) to browser (p5.js), driven by the web's advantages in distribution, accessibility, and networked interaction. This platform shift is not merely technical \u2014 it changes who can access creative coding (anyone with a browser), how work is shared (URL vs. executable), and what kinds of work are possible (networked, collaborative, real-time).",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Documents a significant platform shift in the creative coding ecosystem. The causal chain (technical shift \u2192 accessibility change \u2192 new creative possibilities) is clearly articulated. Relevant to tool design and creative technology adoption.",
    },
    {
        "id": "ART-009",
        "domain": "art",
        "content_type": "principle",
        "source_text": "This book is all about the algorithms. It's about the philosophy, aesthetics, and experimentation too, but mostly it's about the algorithms and the tools you use to explore them. You can, theoretically, perform the mathematics behind procedural generative art with a stick of chalk and a large flat rock, but that would make life unnecessarily difficult \u2014 especially when we live among the ever-advancing sophistication of modern computing.",
        "source_book": "Generative Art: A Practical Guide \u2014 Matt Pearson",
        "expected_principles": [
            "The value of computational tools in generative art is not that they enable something previously impossible \u2014 the underlying mathematics can be executed with chalk and rock \u2014 but that they collapse the iteration cycle from hours to milliseconds. Fast feedback transforms the creative process from planning to exploration: the artist can try, see, adjust, and try again at the speed of thought.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Reframes the role of computation in art: not enabling the impossible, but accelerating the possible to the point where the creative process qualitatively changes. The 'chalk and rock' thought experiment is a powerful illustration of the speed-feedback principle.",
    },
    {
        "id": "SYS-001",
        "domain": "systems_decision",
        "content_type": "principle",
        "source_text": "In these experiments, an animal or person is made to learn which of two simple stimuli, e.g., two geometrical patterns, is tied to a reward. Since there is no sensible connection between the visual sign and the reward, the task is intellectually unattractive, though practically gainful. The best the rat or monkey or human subject can do is to find out by repeated trials which figure is the winner.",
        "source_book": "Visual Thinking \u2014 Rudolf Arnheim",
        "expected_principles": [
            "When there is no structural relationship between a stimulus and its associated reward, learning degrades to trial-and-error \u2014 a cognitively uninteresting process that produces fragile knowledge. Meaningful learning requires structural congruence: the relationship between sign and outcome must be perceivable, not arbitrary. This principle applies to interface design, education, and any system where humans must learn associations.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Bridges perceptual psychology (Arnheim) with learning theory. The 'no sensible connection \u2192 trial-and-error \u2192 fragile knowledge' causal chain has direct implications for UX design, educational technology, and data visualization.",
    },
    {
        "id": "PT-001",
        "domain": "design",
        "content_type": "process_template",
        "source_text": "The design process moves through distinct phases: first, unrestrained ideation where quantity matters more than quality \u2014 sketching feverishly without editing. Second, selection \u2014 identifying the strongest directions from the raw material. Third, refinement \u2014 polishing the chosen direction through iteration. Finally, production \u2014 preparing the finished work for its intended medium. Skipping or compressing the ideation phase produces safe, derivative work because the designer never explored beyond their first ideas.",
        "source_book": "Principles of Logo Design \u2014 George Bokhua",
        "expected_principles": [
            "The logo design process follows four sequential phases: (1) Ideation \u2014 unrestrained sketching for volume, no editing; (2) Selection \u2014 identifying strongest directions; (3) Refinement \u2014 iterative polishing; (4) Production \u2014 final output preparation. The ideation phase is the most commonly skipped, and skipping it produces safe, derivative results because the designer settles for their first ideas rather than discovering breakthrough concepts through exploration.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "First process_template example. Describes a repeatable 4-phase method with clear inputs, outputs, and failure modes. The warning about skipping ideation is the key insight \u2014 it explains WHY the process matters, not just WHAT the steps are.",
    },
    {
        "id": "PT-002",
        "domain": "personal_practice",
        "content_type": "process_template",
        "source_text": "The Four Laws of Behavior Change provide a framework for building any habit: (1) Make it Obvious \u2014 design your environment so the cue is impossible to miss; (2) Make it Attractive \u2014 bundle the behavior with something you already want to do; (3) Make it Easy \u2014 reduce friction to the absolute minimum, aim for two minutes or less; (4) Make it Satisfying \u2014 provide immediate reinforcement so your brain registers the behavior as worth repeating. To break a bad habit, simply invert each law: make it invisible, unattractive, difficult, and unsatisfying.",
        "source_book": "Atomic Habits \u2014 James Clear",
        "expected_principles": [
            "The Four Laws of Behavior Change form a complete framework for habit formation: (1) Make it Obvious (cue design); (2) Make it Attractive (temptation bundling); (3) Make it Easy (friction reduction, two-minute rule); (4) Make it Satisfying (immediate reinforcement). Each law can be inverted to break bad habits: make the cue invisible, the behavior unattractive, the action difficult, and the outcome unsatisfying.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Canonical process template from the most widely-read habits book. The four laws are sequential, each with a specific technique. The inversion property (use the same framework to break habits) makes it a complete system, not just a checklist.",
    },
    {
        "id": "PT-003",
        "domain": "art",
        "content_type": "process_template",
        "source_text": "The generative art workflow follows an iterative cycle: (1) Define the rule system \u2014 specify the algorithm, parameters, and constraints that will generate the output; (2) Run the system \u2014 execute the code and observe what emerges; (3) Evaluate the output \u2014 assess whether the result matches intention or surprises in interesting ways; (4) Tune \u2014 adjust parameters, modify rules, or introduce new constraints; (5) Repeat \u2014 iterate until the system produces satisfying results consistently. The key insight is that you are not designing a single output but a space of possible outputs defined by the rule boundaries.",
        "source_book": "Generative Art: A Practical Guide \u2014 Matt Pearson",
        "expected_principles": [
            "The generative art workflow is a five-step iterative cycle: (1) Define rules, parameters, and constraints; (2) Execute and observe output; (3) Evaluate against intention or interesting surprise; (4) Tune parameters and rules; (5) Repeat until satisfying consistency emerges. The workflow's defining characteristic is that the artist designs the rule space, not a single output \u2014 the output is discovered through iteration, not specified in advance.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Process template for generative art practice. The distinction between designing a rule space vs. designing an output is the key mental model that separates this workflow from traditional art processes.",
    },
    {
        "id": "SYS-002",
        "domain": "systems_decision",
        "content_type": "principle",
        "source_text": "Painting and sculpture were among the Mechanical Arts, which required labor and craftsmanship. The high esteem of music and the disdain of the fine arts derived, of course, from Plato, who in his Republic had recommended music for the education of heroes because it made human beings partake in the mathematical order and harmony of the cosmos, located beyond the reach of the senses; whereas the arts of painting and sculpture dealt with mere sensory appearances \u2014 copies of copies, twice removed from truth.",
        "source_book": "Visual Thinking \u2014 Rudolf Arnheim",
        "expected_principles": [
            "Plato's hierarchy of the arts ranked music above painting and sculpture because music was understood as mathematical \u2014 it partook of the abstract order of the cosmos \u2014 while painting and sculpture dealt with sensory appearances, which Plato considered copies of copies. This philosophical bias against the visual arts as epistemologically inferior shaped Western education for two millennia and explains why visual thinking remains undervalued relative to verbal and mathematical reasoning.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Historical-philosophical principle explaining why visual thinking is systematically undervalued in Western culture. The causal chain (Plato's metaphysics \u2192 educational priorities \u2192 modern bias against visual reasoning) is clearly articulated.",
    },
    {
        "id": "SYS-003",
        "domain": "systems_decision",
        "content_type": "principle",
        "source_text": "The doctrine seems to derive its impetus from an introverted need to view the human mind as the creator of the outer world. It could not otherwise ignore the obvious question of how a language came to develop a particular vocabulary and grammar in the first place; nor would it transfer characteristics of language to perception without acknowledging that perception predates and exceeds language in both evolutionary and developmental terms.",
        "source_book": "Visual Thinking \u2014 Rudolf Arnheim",
        "expected_principles": [
            "The linguistic relativism that claims language determines perception gets the causal arrow backwards: perception predates and exceeds language in both evolutionary history and individual development. Language developed its vocabulary and grammar from pre-existing perceptual categories, not the reverse. Visual thinking is primary; verbal thinking is built on top of it.",
        ],
        "should_extract": True,
        "principle_type": "causal",
        "rationale": "Argues against strong linguistic determinism (Sapir-Whorf) using evolutionary and developmental evidence. Establishes the primacy of visual/perceptual thinking over verbal thinking \u2014 a core thesis of Arnheim's work with implications for education, design, and cognitive science.",
    },
    {
        "id": "AI-001",
        "domain": "ai_computing",
        "content_type": "principle",
        "source_text": "ReAct, short for Reason and Act, is a prompting paradigm that combines Chain of Thought-style reasoning with the ability to perform actions using tools in an interleaved manner. ReAct mimics how humans operate \u2014 we reason verbally and take actions to gather more information or make progress towards a goal. The ReAct pattern involves a loop: the model reasons about what to do, takes an action, observes the result, and reasons again based on the new information.",
        "source_book": "Agentic Design Patterns \u2014 Antonio Gull\u00ed",
        "expected_principles": [
            "The ReAct (Reason + Act) pattern interleaves reasoning and tool-use in a loop: reason \u2192 act \u2192 observe \u2192 reason. This mimics human problem-solving, where thinking and acting are not separate phases but an ongoing cycle \u2014 each action produces new information that informs the next reasoning step. The key insight is that reasoning alone is insufficient for open-ended problems; external information gathered through action is essential.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Defines a foundational AI agent design pattern. The human-analogy framing makes the abstract concept concrete. High relevance to Maxwell OS which uses agentic patterns. The reason\u2192act\u2192observe loop is a reusable architectural primitive.",
    },
    {
        "id": "AI-002",
        "domain": "ai_computing",
        "content_type": "principle",
        "source_text": "The gist here is that if your A/B test result shows that a model is better than another with statistical significance, you can determine which model is indeed better. To measure statistical significance, A/B testing uses statistical hypothesis testing such as two-sample tests. A two-sample test is used to determine whether the difference between two populations is statistically significant.",
        "source_book": "Designing Machine Learning Systems \u2014 Chip Huyen",
        "expected_principles": [
            "Model selection in production ML requires statistical hypothesis testing, not just comparing aggregate metrics. A/B testing with two-sample tests determines whether observed performance differences between models are statistically significant or merely noise. Without statistical rigor, 'model A is better than model B' is an unsupported claim \u2014 the difference could be random variation.",
        ],
        "should_extract": True,
        "principle_type": "procedural",
        "rationale": "Practical ML engineering principle about model evaluation rigor. The distinction between 'observed difference' and 'statistically significant difference' is a common failure point in production ML systems.",
    },
    {
        "id": "SUB-001",
        "domain": "substrate",
        "content_type": "principle",
        "source_text": "In verbal language, modality is typically expressed by modal verbs ('may', 'could', 'would') and adverbs ('possibly', 'certainly', 'unlikely'), whereas in visual communication, modality is expressed through different semiotic resources \u2014 for example, soft focus may be employed to create modality in photographic images, signaling 'this is not a documentary claim but an artistic impression.' Each semiotic mode has its own modality markers, and they do not translate directly between modes.",
        "source_book": "Semiotics of Typography \u2014 Nina N\u00f8rgaard",
        "expected_principles": [
            "Modality \u2014 the expression of 'how true' or 'how real' a representation claims to be \u2014 is expressed differently in each semiotic mode. Verbal language uses modal verbs and adverbs; photography uses soft focus, color saturation, and grain; typography uses weight, serif treatment, and spacing. Because modality markers are mode-specific, they do not translate directly: softening a photograph does not 'mean' the same thing as adding 'possibly' to a sentence.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Core semiotic principle defining modality across modes. The non-translatability insight is important for multimodal design: you cannot simply substitute one mode's markers for another's. Establishes a framework for analyzing truth-claims in visual media.",
    },
    {
        "id": "SUB-002",
        "domain": "substrate",
        "content_type": "principle",
        "source_text": "In multimodal theory, 'mode' and 'modality' refer to very different concepts. While sound, gesture, music, visual images, written and spoken language are seen as different communicative 'modes' of meaning, 'modality' refers to various semiotic resources for expressing 'as how true' or 'as how real' something is represented. A photograph can claim high modality ('this is documentary truth') or low modality ('this is a dream sequence') through its formal properties alone.",
        "source_book": "Semiotics of Typography \u2014 Nina N\u00f8rgaard",
        "expected_principles": [
            "In multimodal communication theory, 'mode' and 'modality' are distinct concepts: a mode is a channel of meaning (sound, image, text, gesture), while modality is the truth-status a representation claims within its mode. Every mode has its own range of modality markers \u2014 visual softness signals 'artistic impression,' while verbal hedges signal 'uncertainty.' Understanding this distinction is essential for analyzing how media construct credibility.",
        ],
        "should_extract": True,
        "principle_type": "definitional",
        "rationale": "Clarifies a critical terminological distinction in semiotics that is often confused. The mode/modality distinction is foundational for any analysis of how media construct truth-claims, with applications in design, journalism, advertising, and AI-generated media.",
    },
    {
        "id": "NEG-HARD-004",
        "domain": "multi_domain",
        "content_type": "principle",
        "source_text": "Design is everywhere. From the chair you're sitting on to the phone in your pocket, design shapes every aspect of modern life. Good design makes things easier to use, more beautiful to look at, and more meaningful to own. Bad design frustrates, confuses, and alienates. The best designers understand this responsibility and strive to create experiences that delight users at every touchpoint.",
        "source_book": "Synthetic \u2014 vague design platitude test",
        "expected_principles": [
        ],
        "should_extract": False,
        "principle_type": "platitude",
        "rationale": "HARD NEGATIVE for design domain. This reads like a design principle but contains zero specific mechanism. 'Good design makes things easier' is unfalsifiable \u2014 it defines good design by its outcomes without specifying what makes design good. The LLM must resist extracting this despite its plausible structure and domain-appropriate vocabulary.",
    },
    {
        "id": "NEG-HARD-005",
        "domain": "multi_domain",
        "content_type": "principle",
        "source_text": "I once attended a workshop where the facilitator asked us to draw our creative process. Everyone's drawing was completely different \u2014 some drew spirals, others drew straight lines, one person drew a tree. It was fascinating to see how differently we all think about creativity. The exercise really opened my eyes to the diversity of creative approaches. Since that workshop, I've tried to be more open-minded about how other people work.",
        "source_book": "Synthetic \u2014 over-narrow personal anecdote",
        "expected_principles": [
        ],
        "should_extract": False,
        "principle_type": "anecdote",
        "rationale": "HARD NEGATIVE. This is a personal anecdote that gestures at a principle ('creative processes differ') but provides only a single-session observation with no generalizable mechanism, no testable claim, and no actionable insight. It's a story, not a principle. The LLM must resist the temptation to extract 'creative processes are diverse' as a principle \u2014 that's a truism, not an insight.",
    },
    {
        "id": "NEG-HARD-006",
        "domain": "multi_domain",
        "content_type": "principle",
        "source_text": "AI is transforming everything. From healthcare to education, from transportation to entertainment, artificial intelligence is reshaping industries at an unprecedented pace. Companies that fail to adopt AI will be left behind. The future belongs to those who embrace artificial intelligence and integrate it into every aspect of their operations. The AI revolution is not coming \u2014 it's already here.",
        "source_book": "Synthetic \u2014 AI hype platitude test",
        "expected_principles": [
        ],
        "should_extract": False,
        "principle_type": "platitude",
        "rationale": "HARD NEGATIVE for AI domain. All hype, no mechanism. 'AI is transforming everything' is unfalsifiable and non-specific. The LLM must resist extracting this \u2014 it has the rhythm and confidence of a principle but contains zero actionable or testable content. Domain-appropriate platitudes are the hardest negatives because they use the right vocabulary.",
    },
]